//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicPop.BusinessLogic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=picpop;AccountKey=0q2eePlT+9nQhNjogqH+" +
            "7NsjddKcTxw4QbZ0WEf/zBZmTq7VuWylyR/iMrYOtHXQg9EXgc/W4d/Lv7nZsn/1Aw==")]
        public string StorageConnectionString {
            get {
                return ((string)(this["StorageConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/PicPop.csdl|res://*/PicPop.ssdl|res://*/PicPop.msl;provider=System.Data.SqlClient;provider connection string=""data source=ane2hqtgp6.database.windows.net;initial catalog=PicPop;persist security info=True;user id=PicPop;password=Admin101;multipleactiveresultsets=True;application name=EntityFramework""")]
        public string PicPopConnectionString {
            get {
                return ((string)(this["PicPopConnectionString"]));
            }
        }
    }
}
