//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicPop.BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlobFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlobFile()
        {
            this.PicPopImages = new HashSet<PicPopImage>();
        }
    
        public int Id { get; set; }
        public string Filename { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public string BlobKey { get; set; }
        public int Container { get; set; }
        public string Type { get; set; }
        public System.DateTime dtCreated { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicPopImage> PicPopImages { get; set; }
    }
}
